-- MODEL CREATED TO POPULATE CUSTOMER DATA (INVOICES AND CONTRACTS) FROM SPECIFIC SOURCE FOLLOWING CERTAIN PROPERTIES -- 


{{ config(materialized='table') }}

//---- *CTEs to collect properties from both Invoices and Contracts * //
WITH COMMON_PROPER AS (
    SELECT 
        PP.CLASSCD, 
        PPM.DESCR, 
        PP.PROPCD, 
        PPM.EDICD
    FROM {{ref("stg_table1")}} PP
    LEFT JOIN {{ref("stg_table2")}} PPM 
    ON PP.VALCD = PPM.VALCD AND PP.PROPCD = PPM.PROPCD
),
INVOICES AS (
    SELECT 
        SM.CUSTOMERCODE, 
        SM.COUNTRYCODE,
        CONCAT(SM.COUNTRYCODE, '00') AS COUNTRYCODE_KEY, 
        CA.DESCR AS INVOICECOUNTRYNAME, 
        MA.DESCR AS MARKETAREA, 
        GA.DESCR AS GEOGRAPHICALAREA,
        SAI.EDICD AS SALESDIRECTORID, 
        SA.DESCR AS SALESDIRECTOR
    FROM {{ref("stag_invoices")}} SM
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'LAND08') MA 
    ON CONCAT(SM.COUNTRYCODE, '00') = MA.CLASSCD
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'LAND07') GA 
    ON CONCAT(SM.COUNTRYCODE, '00') = GA.CLASSCD
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'LAND01') CA 
    ON CONCAT(SM.COUNTRYCODE, '00') = CA.CLASSCD
    LEFT JOIN (SELECT CLASSCD, EDICD FROM COMMON_PROPER WHERE PROPCD = 'WPSD') SAI 
    ON SAI.CLASSCD = CONCAT(SM.COUNTRYCODE, '00')
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'WPSD') SA 
    ON SA.CLASSCD = CONCAT(SM.COUNTRYCODE, '00')
),
CONTRACTS AS (
    SELECT 
        CM.CUSTOMERCODE, 
        CM.COUNTRYCODE,
        CONCAT(CM.COUNTRYCODE, '00') AS COUNTRYCODE_KEY, 
        CA.DESCR AS CONTRACTCOUNTRYNAME, 
        MA.DESCR AS MARKETAREA, 
        GA.DESCR AS GEOGRAPHICALAREA,
        SAI.EDICD AS SALESDIRECTORID, 
        SA.DESCR AS SALESDIRECTOR
    FROM {{ref("stg_contracts")}} CM
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'LAND08') MA 
    ON CONCAT(CM.COUNTRYCODE, '00') = MA.CLASSCD
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'LAND07') GA 
    ON CONCAT(CM.COUNTRYCODE, '00') = GA.CLASSCD
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'LAND01') CA 
    ON CONCAT(CM.COUNTRYCODE, '00') = CA.CLASSCD
    LEFT JOIN (SELECT CLASSCD, EDICD FROM COMMON_PROPER WHERE PROPCD = 'WPSD') SAI 
    ON SAI.CLASSCD = CONCAT(CM.COUNTRYCODE, '00')
    LEFT JOIN (SELECT CLASSCD, DESCR FROM COMMON_PROPER WHERE PROPCD = 'WPSD') SA 
    ON SA.CLASSCD = CONCAT(CM.COUNTRYCODE, '00')
),
COMBINED_PROPERTIES AS (
    SELECT * FROM INVOICES
    UNION ALL
    SELECT * FROM CONTRACTS
),
----create distinct list of customers from invoices and contracts
CUSTOMERS AS (
    SELECT 
        CUSTOMERCODE,
        CUSTOMERNAME,
        COUNTRYCODE
    FROM {{ ref('Customer_list') }}
),
---Combine above customers and properties 
a_combined AS (
    SELECT 
        C.CUSTOMERCODE,
        C.CUSTOMERNAME,
        C.COUNTRYCODE,
        CONCAT(C.COUNTRYCODE, '00') AS COUNTRYCODE_KEY,
        P.INVOICECOUNTRYNAME,
        P.MARKETAREA,
        P.GEOGRAPHICALAREA,
        P.SALESDIRECTORID,
        P.SALESDIRECTOR,
        CLS."Classification"
    FROM CUSTOMERS C
    LEFT JOIN COMBINED_PROPERTIES P
    ON CONCAT(C.COUNTRYCODE, '00') = P.COUNTRYCODE_KEY
    LEFT JOIN {{ref("stg_classification")}} CLS
    ON C.CUSTOMERCODE = CLS."sap_id"
)

    'source1' AS SOURCEDATA, 
    NULL AS INVOCUSTCD, 
    a.CUSTOMERCODE AS SAPCUSTOMERID, 
    CONCAT(a.CUSTOMERCODE, '_', a.COUNTRYCODE, '_', a.COUNTRYCODE, '00')  AS CUSTOMERID, 
    a.CUSTOMERNAME AS CUSTOMERNAME,
    COALESCE(a."Classification", 'D') AS CLASSIFICATION, 
    a.INVOICECOUNTRYNAME AS DELIVERYDISTRICTNAME, 
    CONCAT(a.COUNTRYCODE, '00') AS DELIVERYDISTRICTCODE, 
    a.INVOICECOUNTRYNAME, 
    a.COUNTRYCODE AS INVOICECOUNTRYCODE, 
    MARKETAREA, 
    GEOGRAPHICALAREA, 
    SALESDIRECTOR, 
    NULL AS CUSTOMERSEGMENT, 
    NULL AS FOR_ORDERBOOK, 
    NULL AS SALESPERSON, 
    SALESDIRECTORID
FROM CUSTOMERS
LEFT JOIN a_combined AS a 
    ON a.CUSTOMERCODE = CUSTOMERS.customercode 
    AND a.CountryCode = CUSTOMERS.CountryCode
